title: Emil Javadli # your name (or website title) here
logo: "/images/EJ_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Inspired data scientist 
  <br><br>
  After gaining 8+ years of experience in finance and accounting, I have made the decision to transition to a career in data science. Please refer to the projects section on the right side of this page to view examples of my work, which I have implemented independently.
  <br><br>
  I am currently employed as a finance analyst in the Reporting and Analysis department at Shell.
  <br><br>
  <a href="https://github.com/EmilJavadli">View My GitHub Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/emil-javadli-182711a6/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
